### PR TITLE
Add required libtool installation

### PR DESCRIPTION
**Pull request by carlossg**
Also required ruby and ruby-dev
Fix formatting

### CODE REVIEW

**Comment by ssk2** [comment]
@carlossg - is it necessary to use `sudo` with `gem install fpm`?

**Comment by carlossg** [comment]
If you install ruby system wide and fpm, yes. You could have rvm or something else to do it differently

**Comment by ssk2** [comment]
Got it!

**Comment by ssk2** [comment]
Thank you!

**Pull request merged**
